import type { AdminActivityLog, Conversation, MediaHighlight, Message, MockClient, ProfessionalAd, Report, Review, WeeklySignup } from "./types";

export const states = ["SP", "RJ", "MG", "PR", "SC", "RS"];
export const cities = ["Sao Paulo", "Campinas", "Santos", "Rio de Janeiro", "Belo Horizonte", "Curitiba"];
export const categories = ["Feminina", "Masculino", "Trans", "Casais"];

export const locationsData = [
  { city: "São Paulo", state: "SP" },
  { city: "Rio de Janeiro", state: "RJ" },
  { city: "Belo Horizonte", state: "MG" },
  { city: "Aracaju", state: "SE" },
  { city: "Curitiba", state: "PR" },
  { city: "Salvador", state: "BA" },
  { city: "Florianópolis", state: "SC" },
  { city: "Porto Alegre", state: "RS" },
  { city: "Brasília", state: "DF" },
  // Adicione outras cidades conforme necessário
];

export const ads: ProfessionalAd[] = [
  {
    id: "1",
    slug: "luna-velvet-sao-paulo",
    displayName: "Luna",
    artisticName: "Luna Velvet",
    city: "Sao Paulo",
    state: "SP",
    neighborhood: "Itaim Bibi",
    category: "Feminino",
    shortDescription: "Atendimento discreto com experiencia premium e ambiente reservado.",
    description: "Perfil verificado, atendimento com foco em elegancia, pontualidade e seguranca.",
    serviceDescription: "Atendimento discreto, com foco em conforto, pontualidade e privacidade.",
    startingPrice: 450,
    age: 27,
    heightCm: 170,
    weightKg: 59,
    ethnicity: "Branca",
    eyeColor: "Verdes",
    hairType: "Liso",
    hairColor: "Castanho",
    services: ["Jantar", "Companhia", "Evento social", "Atendimento em hotel"],
    serviceOptions: ["Acompanhamento em festas/eventos/restaurantes", "Sexo presencial", "Pernoite"],
    fetishOptions: ["Podolatria", "Submissao"],
    fetishCustom: "Atendo combinacoes personalizadas sob acordo previo.",
    pricingTable: [
      { label: "1 hora", price: 450 },
      { label: "2 horas", price: 800 },
      { label: "Pernoite", price: 1900 },
    ],
    status: "livre",
    adTier: "premium",
    images: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=900&q=80",
    ],
    rating: 4.9,
    reviewsCount: 128,
    profileViews: 21450,
    verificationStatus: "published",
    submittedAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "2",
    slug: "valentina-noir-campinas",
    displayName: "Valentina",
    artisticName: "Valentina Noir",
    city: "Campinas",
    state: "SP",
    neighborhood: "Cambui",
    category: "Feminino",
    shortDescription: "Conversas inteligentes e experiencia acolhedora com alto nivel de discricao.",
    description: "Atendimento personalizado, local elegante e total respeito a privacidade.",
    serviceDescription: "Atendimento acolhedor com foco em conversa, educacao e discricao.",
    startingPrice: 380,
    age: 31,
    heightCm: 165,
    weightKg: 56,
    ethnicity: "Parda",
    eyeColor: "Castanhos",
    hairType: "Ondulado",
    hairColor: "Preto",
    services: ["Companhia", "Jantar", "Viagens curtas"],
    serviceOptions: ["Acompanhamento em festas/eventos/restaurantes", "Sexo virtual com video chamada"],
    fetishOptions: ["Roleplay/Fantasia", "Dirty talk"],
    fetishCustom: "Disponivel para experiencias personalizadas mediante alinhamento previo.",
    pricingTable: [
      { label: "1 hora", price: 380 },
      { label: "2 horas", price: 690 },
      { label: "4 horas", price: 1250 },
    ],
    status: "em_atendimento",
    adTier: "normal",
    images: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=80",
    ],
    rating: 4.8,
    reviewsCount: 92,
    profileViews: 18670,
    verificationStatus: "published",
    submittedAt: "2026-01-12T10:00:00.000Z",
  },
  {
    id: "3",
    slug: "alex-rivera-rio",
    displayName: "Alex",
    artisticName: "Alex Rivera",
    city: "Rio de Janeiro",
    state: "RJ",
    neighborhood: "Ipanema",
    category: "Masculino",
    shortDescription: "Perfil verificado para eventos e companhia com postura profissional.",
    description: "Atendimento discreto com foco em conforto, conversa e presenca marcante.",
    serviceDescription: "Companhia para eventos e atendimentos com postura profissional e sigilo.",
    startingPrice: 420,
    age: 29,
    heightCm: 182,
    weightKg: 78,
    ethnicity: "Latino",
    eyeColor: "Castanhos escuros",
    hairType: "Curto",
    hairColor: "Castanho",
    services: ["Eventos", "Companhia", "Acompanhamento corporativo"],
    serviceOptions: ["Acompanhamento em festas/eventos/restaurantes"],
    fetishOptions: [],
    fetishCustom: "",
    pricingTable: [
      { label: "1 hora", price: 420 },
      { label: "2 horas", price: 760 },
      { label: "Pernoite", price: 1800 },
    ],
    status: "indisponivel",
    adTier: "premium",
    images: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&w=900&q=80",
    ],
    rating: 4.7,
    reviewsCount: 57,
    profileViews: 17420,
    verificationStatus: "published",
    submittedAt: "2026-01-15T10:00:00.000Z",
  },
  {
    id: "4",
    slug: "maya-aurora-curitiba",
    displayName: "Maya",
    artisticName: "Maya Aurora",
    city: "Curitiba",
    state: "PR",
    neighborhood: "Batel",
    category: "Trans",
    shortDescription: "Atendimento premium com discricao e suporte completo na plataforma.",
    description: "Perfil com verificacao ativa e atendimento de alto padrao em ambiente seguro.",
    serviceDescription: "Atendimento premium com foco em elegancia, pontualidade e conforto.",
    startingPrice: 520,
    age: 26,
    heightCm: 175,
    weightKg: 64,
    ethnicity: "Branca",
    eyeColor: "Azuis",
    hairType: "Longo",
    hairColor: "Loiro",
    services: ["Companhia", "Eventos", "Atendimento em hotel"],
    serviceOptions: ["Acompanhamento em festas/eventos/restaurantes", "Sexo presencial", "Pernoite"],
    fetishOptions: ["Dominacao leve", "BDSM leve"],
    fetishCustom: "Aceito personalizacoes dentro de limites acordados previamente.",
    pricingTable: [
      { label: "1 hora", price: 520 },
      { label: "2 horas", price: 940 },
      { label: "Pernoite", price: 2100 },
    ],
    status: "em_atendimento",
    adTier: "premium",
    images: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=80",
    ],
    rating: 4.95,
    reviewsCount: 147,
    profileViews: 23990,
    verificationStatus: "published",
    submittedAt: "2026-01-20T10:00:00.000Z",
  },
  {
    id: "5",
    slug: "sophia-lisboa-santos",
    displayName: "Sophia",
    artisticName: "Sophia Lisboa",
    city: "Santos",
    state: "SP",
    neighborhood: "Gonzaga",
    category: "Feminino",
    shortDescription: "Perfil elegante para companhia em encontros e eventos sociais.",
    description: "Atendimento discreto com foco em conforto, empatia e excelente conversa.",
    serviceDescription: "Companhia para eventos e encontros com pontualidade e discricao.",
    startingPrice: 360,
    age: 28,
    heightCm: 168,
    weightKg: 58,
    ethnicity: "Branca",
    eyeColor: "Castanhos",
    hairType: "Liso",
    hairColor: "Castanho",
    services: ["Companhia", "Jantar", "Eventos"],
    serviceOptions: ["Acompanhamento em festas/eventos/restaurantes", "Sexo virtual com video chamada"],
    fetishOptions: ["Roleplay/Fantasia"],
    fetishCustom: "Combinacoes personalizadas mediante alinhamento previo.",
    pricingTable: [
      { label: "1 hora", price: 360 },
      { label: "2 horas", price: 650 },
      { label: "4 horas", price: 1180 },
    ],
    status: "livre",
    adTier: "normal",
    images: [
      "https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",

    ],
    rating: 4.7,
    reviewsCount: 74,
    profileViews: 13240,
    verificationStatus: "published",
    submittedAt: "2026-02-01T10:00:00.000Z",
  },
  {
    id: "6",
    slug: "kiara-santini-belo-horizonte",
    displayName: "Kiara",
    artisticName: "Kiara Santini",
    city: "Belo Horizonte",
    state: "MG",
    neighborhood: "Savassi",
    category: "Feminino",
    shortDescription: "Perfil verificado para companhia com postura profissional.",
    description: "Atendimento cordial e reservado, ideal para momentos com discricao e elegancia.",
    serviceDescription: "Companhia para eventos e encontros sociais com sigilo e profissionalismo.",
    startingPrice: 340,
    age: 24,
    heightCm: 166,
    weightKg: 55,
    ethnicity: "Parda",
    eyeColor: "Mel",
    hairType: "Cacheado",
    hairColor: "Preto",
    services: ["Companhia", "Eventos", "Atendimento em hotel"],
    serviceOptions: ["Acompanhamento em festas/eventos/restaurantes"],
    fetishOptions: [],
    fetishCustom: "Disponibilidade mediante agendamento antecipado.",
    pricingTable: [
      { label: "1 hora", price: 340 },
      { label: "2 horas", price: 620 },
      { label: "Pernoite", price: 1500 },
    ],
    status: "indisponivel",
    adTier: "normal",
    images: [
      "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1512310604669-443f26c35f52?auto=format&fit=crop&w=900&q=80",
    ],
    rating: 4.6,
    reviewsCount: 58,
    profileViews: 10980,
    verificationStatus: "published",
    submittedAt: "2026-02-05T10:00:00.000Z",
  },
  // ── Perfis em análise (pending_review) — visíveis apenas no painel admin ──
  {
    id: "7",
    slug: "camila-santos-sp",
    displayName: "Camila",
    artisticName: "Camila Santos",
    city: "São Paulo",
    state: "SP",
    neighborhood: "Moema",
    category: "Feminino",
    shortDescription: "Atendimento premium com foco em elegancia, pontualidade e privacidade.",
    description: "Perfil em processo de verificacao. Atendimento reservado e de alto padrao para clientes exigentes.",
    serviceDescription: "Atendimento presencial em local proprio, com foco em conforto e discricao.",
    startingPrice: 400,
    heightCm: 168,
    ethnicity: "Parda",
    hairColor: "Castanho",
    services: ["Companhia", "Jantar", "Eventos"],
    serviceOptions: ["Acompanhamento em festas/eventos/restaurantes", "Sexo presencial"],
    fetishOptions: [],
    fetishCustom: "",
    pricingTable: [
      { label: "1 hora", price: 400 },
      { label: "2 horas", price: 720 },
      { label: "Pernoite", price: 1800 },
    ],
    status: "livre",
    adTier: "normal",
    images: [
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?auto=format&fit=crop&w=900&q=80",
    ],
    rating: 0,
    reviewsCount: 0,
    profileViews: 0,
    verificationStatus: "pending_review",
    submittedAt: "2026-06-09T14:22:00.000Z",
  },
  {
    id: "8",
    slug: "isabella-fontes-rj",
    displayName: "Isabella",
    artisticName: "Isabella Fontes",
    city: "Rio de Janeiro",
    state: "RJ",
    neighborhood: "Leblon",
    category: "Feminino",
    shortDescription: "Perfil sofisticado para encontros discretos no Rio de Janeiro.",
    description: "Atendimento de alto padrao com foco em conforto, elegancia e seguranca para ambas as partes.",
    serviceDescription: "Encontros presenciais em local seguro e reservado no Leblon.",
    startingPrice: 480,
    heightCm: 172,
    ethnicity: "Branca",
    hairColor: "Loiro",
    services: ["Companhia", "Jantar", "Atendimento em hotel"],
    serviceOptions: ["Acompanhamento em festas/eventos/restaurantes", "Sexo presencial", "Pernoite"],
    fetishOptions: ["Roleplay/Fantasia"],
    fetishCustom: "Combinacoes sob consulta previa.",
    pricingTable: [
      { label: "1 hora", price: 480 },
      { label: "2 horas", price: 860 },
      { label: "Pernoite", price: 2000 },
    ],
    status: "livre",
    adTier: "premium",
    images: [
      "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?auto=format&fit=crop&w=900&q=80",
    ],
    rating: 0,
    reviewsCount: 0,
    profileViews: 0,
    verificationStatus: "pending_review",
    submittedAt: "2026-06-10T08:05:00.000Z",
  },
  {
    id: "9",
    slug: "nath-oliveira-ssa",
    displayName: "Nath",
    artisticName: "Nath Oliveira",
    city: "Salvador",
    state: "BA",
    neighborhood: "Barra",
    category: "Feminino",
    shortDescription: "Atendimento acolhedor e profissional em Salvador.",
    description: "Ambiente seguro, discricao total e atendimento personalizado para cada cliente.",
    serviceDescription: "Atendimento presencial em local proprio na Barra, Salvador.",
    startingPrice: 320,
    heightCm: 165,
    ethnicity: "Negra",
    hairColor: "Preto",
    services: ["Companhia", "Eventos"],
    serviceOptions: ["Acompanhamento em festas/eventos/restaurantes", "Sexo presencial"],
    fetishOptions: [],
    fetishCustom: "",
    pricingTable: [
      { label: "1 hora", price: 320 },
      { label: "2 horas", price: 580 },
    ],
    status: "livre",
    adTier: "normal",
    images: [
      "https://images.unsplash.com/photo-1526510747491-58f928ec870f?auto=format&fit=crop&w=900&q=80",
    ],
    rating: 0,
    reviewsCount: 0,
    profileViews: 0,
    verificationStatus: "pending_review",
    submittedAt: "2026-06-10T09:47:00.000Z",
  },
  // ── Perfil recusado ──
  {
    id: "10",
    slug: "julia-matos-bsb",
    displayName: "Julia",
    artisticName: "Julia Matos",
    city: "Brasília",
    state: "DF",
    neighborhood: "Asa Sul",
    category: "Feminino",
    shortDescription: "Perfil recusado na primeira analise.",
    description: "Perfil com informacoes inconsistentes ou incompletas.",
    serviceDescription: "Informacoes pendentes de complementacao.",
    startingPrice: 280,
    heightCm: 160,
    ethnicity: "Branca",
    hairColor: "Castanho",
    services: ["Companhia"],
    serviceOptions: [],
    fetishOptions: [],
    fetishCustom: "",
    pricingTable: [
      { label: "1 hora", price: 280 },
    ],
    status: "indisponivel",
    adTier: "normal",
    images: [
      "https://images.unsplash.com/photo-1544717302-de2939b7ef71?auto=format&fit=crop&w=900&q=80",
    ],
    rating: 0,
    reviewsCount: 0,
    profileViews: 0,
    verificationStatus: "rejected",
    submittedAt: "2026-06-08T11:00:00.000Z",
    rejectionReason: "Fotos de perfil nao atendem aos criterios minimos de qualidade. Por favor, reenvie com fotos mais recentes e de boa resolucao.",
  },
];

export const reviews: Review[] = [
  { id: "r1", adId: "1", author: "Cliente verificado", score: 5, comment: "Pontual, educada e super discreta.", createdAt: "2026-02-27" },
  { id: "r2", adId: "1", author: "Cliente premium", score: 5, comment: "Experiencia impecavel do inicio ao fim.", createdAt: "2026-02-21" },
  { id: "r3", adId: "2", author: "Cliente verificado", score: 4, comment: "Excelente conversa e atendimento cordial.", createdAt: "2026-02-25" },
  { id: "r4", adId: "4", author: "Cliente premium", score: 5, comment: "Super profissional e comunicativa.", createdAt: "2026-03-01" },
];

export const mediaHighlights: MediaHighlight[] = [
  { id: "ph1", kind: "foto", category: "Feminino", professionalName: "Luna Velvet", coverUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80", likes: 1820, views: 40210 },
  { id: "ph2", kind: "foto", category: "Masculino", professionalName: "Alex Rivera", coverUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80", likes: 1210, views: 33100 },
  { id: "ph3", kind: "foto", category: "Trans", professionalName: "Maya Aurora", coverUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=900&q=80", likes: 1960, views: 44150 },
  { id: "vd1", kind: "video", category: "Feminino", professionalName: "Valentina Noir", coverUrl: "https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?auto=format&fit=crop&w=900&q=80", likes: 1420, views: 51240 },
  { id: "vd2", kind: "video", category: "Masculino", professionalName: "Alex Rivera", coverUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=900&q=80", likes: 980, views: 28600 },
  { id: "vd3", kind: "video", category: "Trans", professionalName: "Maya Aurora", coverUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=900&q=80", likes: 1670, views: 45870 },
];

export const conversations: Conversation[] = [
  { id: "c1", participantId: "p-luna", contactName: "Luna Velvet", contactStatus: "online", lastMessage: "Posso te receber as 21h.", lastMessageAt: "16:20", unread: 1, currentUserAlias: "Cliente reservado" },
  { id: "c2", participantId: "p-valentina", contactName: "Valentina Noir", contactStatus: "offline", lastMessage: "Confirmei seu agendamento.", lastMessageAt: "15:02", unread: 0 },
  { id: "c3", participantId: "support", contactName: "Suporte Sigillus", contactStatus: "online", lastMessage: "Seu pagamento esta em custodia.", lastMessageAt: "13:11", unread: 0 },
];

export const messages: Message[] = [
  { id: "m1", conversationId: "c1", senderId: "p-luna", senderRole: "profissional", senderDisplayName: "Luna Velvet", from: "other", content: "Oi, vi seu pedido para hoje.", messageType: "text", status: "delivered", sentAt: "16:00", deliveredAt: "16:00" },
  { id: "m2", conversationId: "c1", senderId: "current-user", senderRole: "cliente", senderDisplayName: "Cliente reservado", from: "me", content: "Perfeito, consegue as 21h?", messageType: "text", status: "delivered", sentAt: "16:05", deliveredAt: "16:05" },
  { id: "m3", conversationId: "c1", senderId: "p-luna", senderRole: "profissional", senderDisplayName: "Luna Velvet", from: "other", content: "Consigo sim. Local discreto e seguro.", messageType: "text", status: "delivered", sentAt: "16:08", deliveredAt: "16:08" },
  { id: "m4", conversationId: "c1", senderId: "current-user", senderRole: "cliente", senderDisplayName: "Cliente reservado", from: "me", content: "Fechado. Vou finalizar no app.", messageType: "text", status: "delivered", sentAt: "16:11", deliveredAt: "16:11" },
  { id: "m5", conversationId: "c1", senderId: "p-luna", senderRole: "profissional", senderDisplayName: "Luna Velvet", from: "other", content: "Posso te receber as 21h.", messageType: "text", status: "delivered", sentAt: "16:20", deliveredAt: "16:20" },
];

export const serviceTracking = {
  status: "Em deslocamento",
  estimatedArrival: "18 min",
  checkInCode: "SIG-9412",
  elapsed: "00:42:18",
};

export const dashboardSummary = {
  monthRevenue: 28450,
  completedServices: 46,
  activeAd: true,
  profileViews: 1290,
  conversionRate: 18.2,
};

export const popularSections = [
  { label: "Independencia Financeira", href: "/popular/independencia-financeira", description: "Simule renda e tempo para chegar no primeiro milhao." },
  { label: "Mais avaliadas", href: "/popular/mais-avaliadas", description: "Veja as profissionais com maior media por categoria." },
  { label: "Mais vistas", href: "/popular/mais-vistas", description: "Confira os perfis com mais visualizacoes do momento." },
  { label: "Fotos bombando", href: "/popular/fotos-bombando", description: "Ranking de fotos com mais curtidas e views." },
  { label: "Videos bombando", href: "/popular/videos-bombando", description: "Ranking de videos mais populares da plataforma." },
];

// ── Dados do painel administrativo ──

export const mockClients: MockClient[] = [
  { id: "c1", fullName: "Pedro Oliveira", email: "pedro.oliveira@gmail.com", cpf: "432.156.789-01", city: "São Paulo", state: "SP", registeredAt: "2026-06-09T21:42:00Z", status: "active", totalBookings: 3 },
  { id: "c2", fullName: "Maria Silva", email: "maria.silva@hotmail.com", cpf: "321.654.987-02", city: "Rio de Janeiro", state: "RJ", registeredAt: "2026-06-09T18:11:00Z", status: "active", totalBookings: 7 },
  { id: "c3", fullName: "Carlos Santos", email: "carlos.santos@gmail.com", cpf: "654.321.123-03", city: "Belo Horizonte", state: "MG", registeredAt: "2026-06-08T14:30:00Z", status: "active", totalBookings: 1 },
  { id: "c4", fullName: "Ana Costa", email: "ana.costa@outlook.com", cpf: "789.456.321-04", city: "Curitiba", state: "PR", registeredAt: "2026-06-07T10:20:00Z", status: "active", totalBookings: 12 },
  { id: "c5", fullName: "Lucas Ferreira", email: "lucas.ferreira@gmail.com", cpf: "123.789.456-05", city: "Florianópolis", state: "SC", registeredAt: "2026-06-06T08:45:00Z", status: "active", totalBookings: 5 },
  { id: "c6", fullName: "Juliana Alves", email: "juliana.alves@gmail.com", cpf: "456.123.789-06", city: "Porto Alegre", state: "RS", registeredAt: "2026-06-05T16:00:00Z", status: "active", totalBookings: 0 },
  { id: "c7", fullName: "Rafael Souza", email: "rafael.souza@yahoo.com", cpf: "789.123.456-07", city: "Salvador", state: "BA", registeredAt: "2026-06-04T12:30:00Z", status: "active", totalBookings: 2 },
  { id: "c8", fullName: "Fernanda Lima", email: "fernanda.lima@gmail.com", cpf: "321.789.123-08", city: "Brasília", state: "DF", registeredAt: "2026-06-01T09:00:00Z", status: "suspended", suspensionReason: "Comportamento inadequado relatado por profissional verificada.", totalBookings: 4 },
];

export const adminActivityLog: AdminActivityLog[] = [
  { id: "a1", action: "profile_approved", targetName: "Maya Aurora", targetId: "4", adminEmail: "admin@sigillus.dev", timestamp: "2026-06-10T11:30:00Z" },
  { id: "a2", action: "profile_rejected", targetName: "Julia Matos", targetId: "10", adminEmail: "admin@sigillus.dev", reason: "Fotos não atendem aos critérios mínimos de qualidade.", timestamp: "2026-06-10T09:15:00Z" },
  { id: "a3", action: "profile_submitted", targetName: "Isabella Fontes", targetId: "8", timestamp: "2026-06-10T08:05:00Z" },
  { id: "a4", action: "client_registered", targetName: "Pedro Oliveira", targetId: "c1", timestamp: "2026-06-09T21:42:00Z" },
  { id: "a5", action: "client_registered", targetName: "Maria Silva", targetId: "c2", timestamp: "2026-06-09T18:11:00Z" },
  { id: "a6", action: "profile_submitted", targetName: "Camila Santos", targetId: "7", timestamp: "2026-06-09T14:22:00Z" },
  { id: "a7", action: "account_suspended", targetName: "Fernanda Lima", targetId: "c8", adminEmail: "admin@sigillus.dev", reason: "Comportamento inadequado.", timestamp: "2026-06-09T12:00:00Z" },
  { id: "a8", action: "profile_approved", targetName: "Luna Velvet", targetId: "1", adminEmail: "admin@sigillus.dev", timestamp: "2026-06-08T16:00:00Z" },
];

export const weeklySignupsData: WeeklySignup[] = [
  { label: "Seg", clients: 2, professionals: 0 },
  { label: "Ter", clients: 3, professionals: 1 },
  { label: "Qua", clients: 1, professionals: 0 },
  { label: "Qui", clients: 4, professionals: 2 },
  { label: "Sex", clients: 2, professionals: 1 },
  { label: "Sáb", clients: 3, professionals: 0 },
  { label: "Dom", clients: 1, professionals: 1 },
];

// ── Denúncias ──

export const mockReports: Report[] = [
  {
    id: "rep1",
    type: "fake_profile",
    reporterName: "Pedro Oliveira",
    reporterRole: "cliente",
    reportedName: "Julia Matos",
    reportedId: "10",
    reportedRole: "profissional",
    description: "O perfil não bate com as fotos enviadas. A profissional parece ser outra pessoa nas fotos.",
    status: "pending",
    createdAt: "2026-06-10T15:30:00Z",
  },
  {
    id: "rep2",
    type: "harassment",
    reporterName: "Luna Velvet",
    reporterRole: "profissional",
    reportedName: "Fernanda Lima",
    reportedId: "c8",
    reportedRole: "cliente",
    description: "A cliente enviou mensagens ameacadoras após o cancelamento de um atendimento, incluindo ameaças de divulgação de dados pessoais.",
    status: "resolved",
    resolution: "Conta suspensa. Investigação confirmou as ameaças via chat.",
    createdAt: "2026-06-09T11:00:00Z",
    updatedAt: "2026-06-09T12:00:00Z",
  },
  {
    id: "rep3",
    type: "scam",
    reporterName: "Maria Silva",
    reporterRole: "cliente",
    reportedName: "Camila Santos",
    reportedId: "7",
    reportedRole: "profissional",
    description: "Recebi o pagamento antecipado mas a profissional não compareceu e não responde mais mensagens.",
    status: "under_review",
    createdAt: "2026-06-09T20:00:00Z",
    updatedAt: "2026-06-10T09:00:00Z",
  },
  {
    id: "rep4",
    type: "inappropriate_content",
    reporterName: "Carlos Santos",
    reporterRole: "cliente",
    reportedName: "Nath Oliveira",
    reportedId: "9",
    reportedRole: "profissional",
    description: "Perfil contém fotos que violam as diretrizes da plataforma. Conteúdo explicitão não autorizado.",
    status: "pending",
    createdAt: "2026-06-10T08:15:00Z",
  },
  {
    id: "rep5",
    type: "other",
    reporterName: "Ana Costa",
    reporterRole: "cliente",
    reportedName: "Isabella Fontes",
    reportedId: "8",
    reportedRole: "profissional",
    description: "A profissional pediu para fazer o pagamento fora da plataforma para evitar taxas.",
    status: "dismissed",
    resolution: "Orientamos a cliente sobre o uso da plataforma. Sem evidências de fraude.",
    createdAt: "2026-06-08T14:00:00Z",
    updatedAt: "2026-06-09T10:00:00Z",
  },
  {
    id: "rep6",
    type: "harassment",
    reporterName: "Rafael Souza",
    reporterRole: "cliente",
    reportedName: "Maya Aurora",
    reportedId: "4",
    reportedRole: "profissional",
    description: "Após recusar um atendimento, a profissional passou a enviar mensagens hostis e depreciar o cliente no chat.",
    status: "pending",
    createdAt: "2026-06-10T17:45:00Z",
  },
];

